[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.0"
dependencies = [
    "msgpack>=1.0.5",
    "onnx>=1.12.0",
    "tensorflow>=2.3.4",
    "torch>=1.5.1",
]

[tool.pyright]
venv = ".venv"
venvPath = "."
